pokemoncollector/main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('pokemon/', views.pokemon_index, name='index'),
    path('pokemon/<int:pokemon_id>/', views.pokemon_detail, name='detail'),
    path('pokemon/create/', views.PokemonCreate.as_view(), name='pokemon_create'),
    path('pokemon/<int:pk>/update/', views.PokemonUpdate.as_view(), name='pokemon_update'),
    path('pokemon/<int:pk>/delete/', views.PokemonDelete.as_view(), name='pokemon_delete'),
    path('pokemon/<int:pokemon_id>/add_feeding/', views.add_feeding, name='add_feeding'),
]

pokemoncollector/pokemoncollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

pokemoncollector/main_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
MEALS = (
    ('B', 'Breakfast'),
    ('L', 'Lunch'),
    ('D', 'Dinner')
)
class Pokemon(models.Model):
    name = models.CharField(max_length= 100, default='SOME CHAR')
    description = models.TextField(max_length= 100, default='SOME TEXT')
    attack = models.CharField(max_length= 100, default='SOME CHAR')
    weakness = models.CharField(max_length= 100, default='SOME CHAR')
    age = models.IntegerField()
    toys = models.ManyToManyField(Toy)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('detail', kwargs={'pokemon_id': self.id})


class Feeding(models.Model):
  date = models.DateField()
  meal = models.CharField(max_length=1,
    # add the 'choices' field option
    choices=MEALS,
    # set the default value for meal to be 'B'
    default=MEALS[0][0])
    # Create a cat_id FK
pokemon = models.ForeignKey(Pokemon, on_delete=models.CASCADE)
    def __str__(self):
        # Nice method for obtaining the friendly value of a Field.choice
        return f"{self.get_meal_display()} on {self.date}"
            class Meta:
            ordering = ['-date']

class Toy(models.Model):
    name: models.CharField(max_length= 100, default="Name")
    color: models.CharField(max_length= 100, default="Color")

pokemoncollector/main_app/templates/main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
  class Meta:
    model = Feeding
    fields = ['date', 'meal']

pokemoncollector/main_app/views.py
# Add the following import
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Pokemon
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from .forms import FeedingForm



# class Pokemon:
#     def __init__(self, name, description, attack, weakness, age):
#         self.name = name
#         self.description = description
#         self.attack = attack
#         self.weakness = weakness
#         self.age = age

# pokemon = [
#     Pokemon('Charmander', 'Fire-lizard', 'ember', 'rain', 3),
#     Pokemon('Bulbasour', 'Plant-dinarour thing', 'razor leaf','spicy food', 65000000000),
#     Pokemon('Squertal', 'Water-turtle', 'water gun', 'the quilted quicker picker upper', 4)
# ]


# Define the home view
def home(request):
  return render(request, 'home.html')

def about(request):
  return render(request, 'about.html')

def pokemon_index(request):
    pokemon = Pokemon.objects.all()
    return render(request, 'pokemon/index.html', { 'pokemon': pokemon })

def pokemon_detail(request, pokemon_id):
  pokemon = Pokemon.objects.get(id=pokemon_id)
  feeding_form = FeedingForm()
  return render(request, 'pokemon/detail.html', { 
    'pokemon': pokemon, 
    'feeding_form': feeding_form, 
    'toys': toys_cat_doesnt_have
 })

def add_feeding(request, cat_id):
  # create the ModelForm using the data in request.POST
  form = FeedingForm(request.POST)
  # validate the form
  if form.is_valid():
    # don't save the form to the db until it
    # has the cat_id assigned
    new_feeding = form.save(commit=False)
    new_feeding.cat_id = cat_id
    new_feeding.save()
  return redirect('detail', pokemon_id=pokemon_id)

class PokemonCreate(CreateView):
  model = Pokemon
  fields = '__all__'
  success_url = '/pokemon/'

class PokemonUpdate(UpdateView):
  model = Pokemon
  # Let's make it impossible to rename a cat :)
  fields = ['name', 'description', 'age']

class PokemonDelete(DeleteView):
  model = Pokemon
  success_url = '/pokemon/'

pokemoncollector/main_app/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Pokemon Collector</title>
</head>
<body>
    {% extends 'base.html' %}
    {% block content %}
        
    <h1>About the Pokemon Collector</h1>
    <hr />
    <p>Hire the Pokemon Collector!</p>
    
    {% endblock %}
    <footer>All Rights Reserved, &copy; 2019 Pokemon Collector</footer>
</body>
</html>

pokemoncollector/main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Pokemon Collector</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


</head>
<body>
    <header class="navbar-fixed">
        <nav>
            <div class="nav-wrapper">
                <ul>
                    <li><a href="/" class="left brand-logo">&nbsp;&nbsp;PokemonCollector</a></li>
                </ul>
                <ul class="right">
                        <li><a href="{% url 'about' %}">About</a></li>
                        <li><a href="{% url 'index' %}">View All My Pokemon</a></li>
                        <li><a href="{% url 'pokemon_create' %}">Add a Pokemon</a></li>
                    </ul>
            </div>
        </nav>
    </header>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
  	 <footer class="page-footer">
        <footer>All Rights Reserved, &copy; 2019 Pokemon Collector</footer>
    </footer>
</body>
</html>

pokemoncollector/main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<h1>Home</h1>

{% endblock %}

pokemoncollector/main_app/templates/main_app/pokemon_form.html
{% extends 'base.html' %}

{% block content %}
  <!-- Leaving the action empty makes the form post to the same url used to display it -->
  <form action="" method="post">
    <!-- Django requires the following for security purposes -->
    {% csrf_token %}
    <table>
      <!-- Render the inputs inside of <tr>s & <td>s -->
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

pokemoncollector/main_app/templates/pokemon/detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon Details</h1>

<div class="card">
  <div class="card-content">
    <span class="card-title">{{ pokemon.name }}</span>
    <p>Description: {{ pokemon.discription }}</p>
    <p>Attack: {{ pokemon.attack }}</p>
    <p>Weakness: {{ pokemon.weakness }}</p>
    {% if pokemon.age > 0 %}
      <p>Age: {{ pokemon.age }}</p>
    {% else %}
      <p>Age: Egg</p>
    {% endif %}
  </div>
    <a href="{% url 'pokemon_update' pokemon.id %}">Edit</a>
    <a href="{% url 'pokemon_delete' pokemon.id %}">Delete</a>
</div>
<div class="col s6">
    <form action="{% url 'add_feeding' cat.id %}" method="post">
        {% csrf_token %}
          {{ feeding_form.as_p }}
          <input type="submit" class="btn" value="Add Feeding">
        </form>
  <table class="striped">
    <thead>
      <tr><th>Date</th><th>Meal</th></tr>
    </thead>
    <tbody>
      {% for feeding in pokemon.feeding_set.all %}
        <tr>
          <td>{{feeding.date}}</td>
          <td>{{feeding.get_meal_display}}</td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
</div>
<hr>
<div class="row">
  <div class="col s6">
    <h3>{{ pokemon.name }}'s Toys</h3>
    {% if pokemon.toys.count %}
      {% for toy in pokemon.toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>No Toys :(</h5>
    {% endif %}
  </div>
  <div class="col s6">
    <h3>Available Toys</h3>
    {% if toys.count %}
      {% for toy in toys.all %}
        <div class="card">
          <div class="card-content">
            <span class="card-title">
              A <span style="color: {{ toy.color }}">{{ toy.color }}</span> {{ toy.name }}
            </span>
          </div>
          <div class="card-action">
            <form action="" method="post">
              {% csrf_token %}
              <button type="submit" class="btn">Add</button>
            </form>
          </div>
        </div>
      {% endfor %}
    {% else %}
      <h5>{{pokemon.name}} Already Has All Toys Available</h5>
    {% endif %}
  </div>
<script>
var dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  var selectEl = document.getElementById('id_meal');
  M.FormSelect.init(selectEl);
  </script>
{% endblock %}

pokemoncollector/main_app/templates/pokemon/index.html
{% extends 'base.html' %}
{% block content %}

<h1>Pokemon List</h1>

{% for p in pokemon %}
    <div class="card">
    <a href="{% url 'detail' pokemon.id %}">
        <div class="card-content">
            <span class="card-title">{{ pokemon.name }}</span>
            <p>Discription: {{ pokemon.discription }}</p>
            <p>Attack: {{ pokemon.attack }}</p>
            <p>Weakness: {{ pokemon.weakness }}</p>
            {% if pokemon.age > 0 %}
                <p>Age: {{ pokemon.age }}</p>
            {% else %}
                <p>Age: Egg</p>
            {% endif %}
        </div>
    </div>
{% endfor %}

{% endblock %}

pokemoncollector/main_app/templates/pokemon/pokemon_form.html
{% block content %}
  <!-- New if/else block -->
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Cat</h1>
  {% endif %}

pokemoncollector/main_app/templates/pokemon_conferm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Pokemon</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'detail' pokemon.id %}">Cancel</a>
  </form>
{% endblock %}